
from bs4 import BeautifulSoup;from requests import get;
from art import *;from stringcolor import *;
from url64 import *;from random import choice;
class Terminal_banner:
        def __init__(self,**set_Options):
            setattr(self,"Options",(set_Options));
        @property
        def help_me_bro(self):
            return cs("""
            nama class ' Terminal_banner ' dengan parameter sesuai fungsi yang di panggil.
            contoh pemanggilan fungsi : Terminal_banner( parameter ).nama_fungsi
            setiap parameter yang diberikan harus berisi antara key & value,
            ' fungsi pertolongan tampa parameter'
                list_font : menampilkan semua daftar list font.
                list_art : menampilkan semua daftar list art.
                list_decoration : menampilkan semua daftar list decorasi.
            
            fungsi dengan parameter yang diberikan dalam class obj:
                decoration :
                    => decoration -> name decoration.
                    => reverse -> True/False,untuk membalikan decorasi jika ya ketikan True dan sebaliknya.
                    => color -> memberikan warna pada decorasi,
                    => bg_color -> memberikan warna background pada decorasi,jika tidak ada berikan nilai None.
                strings :
                    => string -> masukan string bebas.
                    => color -> memberikan warna pada string.
                    => bg_color -> memberikan warna background pada string,jika tidak ada berikan nilai None.
                textArt :
                    => string -> masukan string bebas.
                    => font -> nama font.
                    => decoration -> nama decorasi.
                    => color -> memberikan warna.
                    => bg_color -> memberikan warna background,jika tidak ada berikan nilai None.
                random_font :
                    'font yang di berikan akan ditampilkan 1 per 1 secara acak'
                    => string -> masukan string bebas.
                    => font1 -> nama font.
                    => font2 -> nama font.
                    => font3 -> nama font.
                    => font4 -> nama font.
                    => color -> memberikan warna pada font.
                    => bg_color -> memberikan warna background pada font, jika tidak ada berikan nilai None.
                font :
                    => string -> masukan string bebas.
                    => font -> nama font.
                    => color -> memberikan warna.
                    => bg_color -> memberikan warna background,jika tidak ada berikan nilai None.
                url_strings(Attribute,Class) :
                    => url -> url/tautan/link
                    => color -> memberikan warna pada text.
                    => memberikan background warna pada text.
                    'jika ingin mengambil content dengan spesifik masukan parameter berdasarkan Attribute & nama class pada fungsi url_strings()'
                list_ascii_art : note > 'memanggil fugsi ini membutuhkan koneksi internet!!'
                    => category ->  nuke
                                    numbers
                                    nun
                                    nunchako
                                    nurse
                                    nursery
                                    nutcracker
                                    nymph
                                    obelix
                                    objects
                                    oboe
                                    observatory
                                    octopus
                                    odie
                                    office
                                    offroad
                                    ogre
                                    oil
                                    oilrig
                                    oilrigs
                                    ok
                                    okapi
                                    oktoberfest
                                    oldtimer
                                    oliveoyl
                                    oliverco
                                    olympics
                                    om
                                    omega
                                    oneline
                                    onion
                                    opel
                                    opera
                                    oracle
                                    orangutan
                                    orc
                                    orca
                                    orchestra
                                    orchid
                                    organ
                                    origami
                                    ornament
                                    ostrich
                                    otter
                                    ottifant
                                    oven
                                    overall
                                    owl
                                    oyster
                                    pacifier
                                    pacman
                                    paddington
                                    paddle
                                    pagoda
                                    pagodas
                                    paint
                                    paintbrush
                                    painter
                                    painting
                                    paintress
                                    palace
                                    palaces
                                    palette
                                    palm
                                    palmtree
                                    pamela
                                    pan
                                    panda
                                    pansies
                                    panther
                                    pants
                                    paper
                                    parabola
                                    parachute
                                    parade
                                    paradise
                                    parakeet
                                    parcel
                                    paris
                                    park
                                    parking
                                    parrot
                                    parthenn
                                    parthenon
                                    party
                                    passion
                                    pasta
                                    pattern
                                    pawprints
                                    payphone
                                    pc
                                    peace
                                    peacepipe
                                    peacock
                                    peanuts
                                    pear
                                    pearl
                                    pee
                                    peek
                                    pegasus
                                    pelican
                                    pen
                                    pencil
                                    penguins
                                    pentagon
                                    pentagram
                                    people
                                    pepper
                                    pepsi
                                    peripatus
                                    periscope
                                    perl
                                    perryrhodan
                                    person
                                    perspective
                                    peru
                                    peterpan
                                    petitprince
                                    petshop
                                    petshopboys
                                    pez
                                    pfennig
                                    phantom
                                    pharaoh
                                    phlippines
                                    phoenix
                                    phone
                                    phonebooth
                                    photo
                                    photographer
                                    pi
                                    piano
                                    picasso
                                    piccolo
                                    pie
                                    pig
                                    pigeon
                                    piggyback
                                    piggybank
                                    piglet
                                    pigs
                                    pigtail
                                    pika
                                    pike
                                    pile
                                    pilgrims
                                    pill
                                    pillow
                                    pinball
                                    pingpong
                                    pinkfloyd
                                    pinkpanther
                                    pinkybrain
                                    pinoc
                                    pinocchio
                                    pint
                                    pinwheel
                                    pipe
                                    piper
                                    pippi
                                    piranha
                                    pirate
                                    pisa
                                    pistol
                                    pixie
                                    pizza
                                    pizzacats
                                    plane
                                    planets
                                    plants
                                    plasma
                                    platypus
                                    playboy
                                    playstation
                                    plesiosaurus
                                    plonk
                                    plug
                                    plumbing
                                    plutonium
                                    plymouth
                                    pocahont
                                    pocketwatch
                                    poem
                                    poet
                                    pogo
                                    pointer
                                    pokemon
                                    poland
                                    polar
                                    police
                                    polo
                                    pontiac
                                    poodle
                                    pooh
                                    pool
                                    poop
                                    pop
                                    popeye
                                    portal
                                    portrait
                                    portugal
                                    pose
                                    poseidon
                                    possum
                                    post
                                    postcard
                                    pot
                                    pots
                                    powerplant
                                    powrang
                                    powrplnt
                                    pram
                                    prayer
                                    prayingmantis
                                    pregnant
                                    present
                                    presskey
                                    pretzel
                                    priest
                                    primitive
                                    prince
                                    princess
                                    pringles
                                    printer
                                    prison
                                    privacy
                                    prize
                                    profile
                                    proposal
                                    proverb
                                    psm
                                    psychiatrist
                                    pteranodon
                                    puke
                                    pull
                                    pulp
                                    pump
                                    pumpkin
                                    punch
                                    punk
                                    puppet
                                    puppy
                                    puzzle
                                    pyjamas
                                    pyramid
                                    pyramids
                                    quake
                                    quarter
                                    quasimodo
                                    queen
                                    question
                                    questionmark
                                    queue
                                    quiet
                                    quill
                                    quiz
                                    quotes
                                    rabbi
                                    rabbit
                                    racoon
                                    radar
                                    radiation
                                    radio
                                    radiotelescope
                                    rain
                                    rainbow
                                    ralf
                                    ram
                                    rapunzel
                                    raskolnikow
                                    rat
                                    rattle
                                    rattlesnake
                                    raven
                                    raygun
                                    raytracer
                                    razor
                                    reading
                                    reaper
                                    rebirth
                                    receipt
                                    recordplayer
                                    records
                                    recycle
                                    redbaron
                                    redbull
                                    reddwarf
                                    redhat
                                    redwings
                                    reflection
                                    refrigerator
                                    reindeer
                                    relax
                                    religion
                                    religious
                                    reptil
                                    rescue
                                    research
                                    resort
                                    restarnt
                                    restroom
                                    revolver
                                    rhino
                                    ribbon
                                    rifle
                                    rikscha
                                    ring
                                    rip
                                    roadrunner
                                    roadworks
                                    robbery
                                    robby
                                    robhood
                                    robin
                                    robot
                                    robots
                                    rock
                                    rockets
                                    rockingchair
                                    rockinghorse
                                    rocky
                                    rockyhorrorshow
                                    rodeo
                                    rollercoaster
                                    rollerskates
                                    rollingpin
                                    roman
                                    romance
                                    romeojuliet
                                    room
                                    rooms
                                    rooster
                                    rope
                                    rosary
                                    rose
                                    rose1
                                    rotflmao
                                    roundabout
                                    rowdy
                                    rowing
                                    rubberduck
                                    rubbishbin
                                    rubik
                                    rugby
                                    ruins
                                    ruler
                                    runes
                                    running
                                    russian
                                    saab
                                    sabre
                                    sack
                                    sacrecouer
                                    sadness
                                    safe
                                    safetypin
                                    sail
                                    sailboat
                                    sailor
                                    sailormoon
                                    sailplane
                                    saint
                                    salmon
                                    salome
                                    saloon
                                    saltpepper
                                    samoa
                                    samurai
                                    sandbox
                                    sandcasl
                                    sandcastle
                                    sandwich
                                    sanfrancisco
                                    santa
                                    satan
                                    satellites
                                    saturn
                                    sausage
                                    saw
                                    sax
                                    saying
                                    scales
                                    scandinavia
                                    scarabaeus
                                    scarecrow
                                    scarf
                                    scater
                                    school
                                    schoolhs
                                    science
                                    scientology
                                    scifi
                                    scissors
                                    scoobydoo
                                    scooter
                                    scorpion
                                    scotch
                                    scotland
                                    scotty
                                    scrabble
                                    scratch
                                    scratchingpost
                                    scream
                                    screw
                                    screwdriver
                                    scroll
                                    scuba
                                    scythe
                                    sea
                                    seagull
                                    seahorse
                                    seal
                                    seaplane
                                    seascape
                                    seashell
                                    seatle
                                    seaveh
                                    seeyou
                                    selfportrait
                                    sendungmitdermaus
                                    sermon
                                    servant
                                    service
                                    sesame
                                    sesamestreet
                                    settee
                                    seven
                                    sewing
                                    shadow
                                    shamrock
                                    shamus
                                    sharks
                                    sheep
                                    shell
                                    shepherd
                                    sheriff
                                    sherlockholmes
                                    shield
                                    ships
                                    shirt
                                    shit
                                    shiva
                                    shoes
                                    shoeshine
                                    shoot
                                    shopping
                                    shops
                                    shortcut
                                    shotgun
                                    shovel
                                    shower
                                    shrubbery
                                    shuriken
                                    shutdown
                                    shuttle
                                    sick
                                    sicklehammer
                                    sideways
                                    siege
                                    siesta
                                    sign
                                    signals
                                    signature
                                    signpost
                                    sikhism
                                    silhouette
                                    sillywalks
                                    silo
                                    silverware
                                    simba
                                    simpsons
                                    sine
                                    singer
                                    sink
                                    sinks
                                    siren
                                    sisyphus
                                    sitting
                                    siverstein
                                    sixpack
                                    skateboard
                                    skating
                                    skeleton
                                    sketch
                                    skiing
                                    skijumper
                                    skijumping
                                    skinhead
                                    skipping
                                    skirt
                                    skull
                                    skulls
                                    skunk
                                    skydiver
                                    skyline
                                    skylines
                                    skyscrap
                                    skyscraper
                                    sledge
                                    sleep
                                    sleepb
                                    sleepingbeauty
                                    sleigh
                                    sleipner
                                    sleuthing
                                    slice
                                    sliderule
                                    slingshot
                                    slipper
                                    slope
                                    sloth
                                    slotmachine
                                    sm
                                    small
                                    smart
                                    smile
                                    smilies
                                    smily
                                    smoke
                                    smurfs
                                    snail
                                    snake
                                    snakecharmer
                                    sneakers
                                    sneeze
                                    snooker
                                    snoopy
                                    snorkel
                                    snow
                                    snowball
                                    snowblower
                                    snowboard
                                    snowflakes
                                    snowglobe
                                    snowman
                                    snowmobile
                                    snowwhit
                                    snuggle
                                    soap
                                    soccer
                                    sock
                                    sofa
                                    sofas
                                    solarsystem
                                    solderingion
                                    soldiers
                                    sombrero
                                    sonic
                                    soroban
                                    sound
                                    soup
                                    sourceress
                                    southpark
                                    soviets
                                    space
                                    spaceinvaders
                                    spacendl
                                    spaceships
                                    spaceshuttle
                                    spades
                                    spam
                                    spaniel
                                    sparrow
                                    speech
                                    sperm
                                    spew
                                    sphere
                                    sphinx
                                    spicegirls
                                    spider
                                    spiderman
                                    spinningwheel
                                    spiral
                                    spitfire
                                    splash
                                    splat
                                    spock
                                    spoon
                                    sports
                                    spraycan
                                    spring
                                    springboard
                                    sprite
                                    spy
                                    squid
                                    squirrel
                                    srilanka
                                    stag
                                    stage
                                    staircase
                                    stairs
                                    stallone
                                    stamps
                                    stapler
                                    star
                                    startrek
                                    startrek1
                                    starwars
                                    starwars1
                                    statement
                                    statue
                                    stealth
                                    steamboat
                                    steamengine
                                    steamer
                                    steamroller
                                    stegosaurus
                                    steno
                                    steps
                                    stereo
                                    stereoram
                                    stethoscope
                                    stexupery
                                    stickman
                                    stickman2
                                    stingray
                                    stirlingengine
                                    stnicholas
                                    stocking
                                    stonehenge
                                    stonehng
                                    stool
                                    stop
                                    stork
                                    storm
                                    story
                                    stove
                                    stpatrick
                                    stpetersburg
                                    streamline
                                    street
                                    strength
                                    strings
                                    striptease
                                    stuka
                                    stumble
                                    subbuteo
                                    submarine
                                    sucker
                                    suicide
                                    suitcase
                                    sumo
                                    sun
                                    sunbath
                                    sunrise
                                    sunset
                                    sunshade
                                    supergirl
                                    superman
                                    surf
                                    surfer
                                    surgery
                                    sushi
                                    svejk
                                    swan
                                    swatter
                                    sweater
                                    sweden
                                    sweets
                                    swimming
                                    swing
                                    switch
                                    switzerland
                                    swordfish
                                    swords
                                    sylt
                                    sylvester
                                    symbol
                                    symbols
                                    syringe
                                    table
                                    tableofelements
                                    tables
                                    tachometer
                                    taichi
                                    tajmahal
                                    takeoff
                                    talk
                                    tamagotchi
                                    tamarin
                                    tampon
                                    tangent
                                    tank
                                    tanning
                                    tap
                                    tapdancing
                                    tape
                                    tapir
                                    tarzan
                                    tasmaniandevil
                                    tattoo
                                    taurus
                                    taxi
                                    taz
                                    tea
                                    teapot
                                    tear
                                    teddy
                                    teenager
                                    teepee
                                    teepees
                                    teeth
                                    telephone
                                    telescope
                                    teletubbies
                                    temple
                                    temples
                                    temptation
                                    tengwar
                                    tennis
                                    tent
                                    tents
                                    terminal
                                    terminator
                                    test
                                    tex
                                    texas
                                    text
                                    texture
                                    thanksgiving
                                    thermom
                                    thermometer
                                    thermos
                                    thief
                                    thing
                                    think
                                    thistle
                                    thought
                                    thousand
                                    threat
                                    threepig
                                    throw
                                    thumpsup
                                    thw
                                    tictactoe
                                    tie
                                    tiefighter
                                    tiffany
                                    tiger
                                    tigerente
                                    tigger
                                    tiling
                                    time
                                    timpany
                                    tinkerbell
                                    tintin
                                    tinytoon
                                    tissues
                                    tit
                                    titanic
                                    toast
                                    toaster
                                    toddler
                                    tofu
                                    tohether
                                    toiletpaper
                                    toilets
                                    tolkien
                                    tom
                                    tomato
                                    tombstone
                                    tomcat
                                    tomthumb
                                    tongue
                                    toolbox
                                    tools
                                    toons
                                    toothbrush
                                    torch
                                    torches
                                    torii
                                    tornado
                                    toronto
                                    torpedo
                                    tortoise
                                    totempole
                                    toucan
                                    touchpad
                                    tourette
                                    tournament
                                    towel
                                    tower
                                    towerbridge
                                    towerofhanoi
                                    towers
                                    town
                                    towrbrdg
                                    toy
                                    toystory
                                    trabant
                                    tractor
                                    traffic
                                    train
                                    tram
                                    transam
                                    transmogrify
                                    transporter
                                    trap
                                    trapdoor
                                    trash
                                    trashcan
                                    travel
                                    treasure
                                    treasureisland
                                    treasuremap
                                    trebuchet
                                    tree
                                    treehous
                                    treehouse
                                    trench
                                    trex
                                    triangle
                                    triarch
                                    trick
                                    trilobite
                                    triomphe
                                    triton
                                    trojanhorse
                                    troll
                                    trolley
                                    trolly
                                    trombone
                                    trophy
                                    trousers
                                    truck
                                    trumpet
                                    tshirt
                                    tuba
                                    tulips
                                    tunnel
                                    turban
                                    turbo
                                    turkey
                                    turntables
                                    turtle
                                    tutorial
                                    tux
                                    tv
                                    tvseries
                                    tweety
                                    twins
                                    twist
                                    typewriter
                                    ufo
                                    uk
                                    umbrella
                                    unhappy
                                    unicorn
                                    unicycles
                                    unihannover
                                    unihnver
                                    unionjack
                                    universe
                                    unix
                                    urinal
                                    urn
                                    usa
                                    usb
                                    user
                                    uzi
                                    valentine
                                    valkyrie
                                    vampire
                                    van
                                    vancouver
                                    vangogh
                                    vanity
                                    varanus
                                    vase
                                    venus
                                    vespa
                                    vice
                                    victorian
                                    video
                                    view
                                    viking
                                    village
                                    villages
                                    villain
                                    vine
                                    viola
                                    violence
                                    violin
                                    vitamins
                                    vms
                                    vodka
                                    volcano
                                    volkswagen
                                    volleyball
                                    volume
                                    vomit
                                    voodoo
                                    vulcano
                                    vulture
                                    vw
                                    waffle
                                    wagtail
                                    wait
                                    waiter
                                    waitress
                                    wales
                                    walk
                                    walkietalkie
                                    walking
                                    wall
                                    wallacegromit
                                    wallpaper
                                    wallpapr
                                    walls
                                    walrus
                                    wand
                                    wanted
                                    war
                                    warner
                                    warnerbros
                                    warrior
                                    wasp
                                    wastedisposal
                                    watch
                                    watchout
                                    watchtower
                                    water
                                    waterfall
                                    wateringcan
                                    waterloo
                                    watermelon
                                    waterski
                                    waterwell
                                    wave
                                    wc
                                    weasel
                                    web
                                    wedding
                                    weed
                                    weightlifting
                                    well
                                    wells
                                    werewolf
                                    western
                                    westminsterabbey
                                    whaam
                                    whale
                                    what
                                    whatsit
                                    wheel
                                    wheelbarrow
                                    wheelchair
                                    whistle
                                    whitehouse
                                    whitehse
                                    whitetower
                                    who
                                    whoiswho
                                    why
                                    wildlife
                                    wilhelmbusch
                                    wilhelmtell
                                    wind
                                    windmill
                                    windows
                                    windsurfing
                                    wine
                                    winnie
                                    winniethepooh
                                    winter
                                    wise
                                    witch
                                    wizard
                                    wodka
                                    wok
                                    wolf
                                    wombat
                                    women
                                    wonderlamp
                                    woodpecker
                                    words
                                    world
                                    worldcup
                                    worm
                                    wormhole
                                    wrapper
                                    wrapping
                                    wreath
                                    wrench
                                    wrestle
                                    write
                                    wstmnstr
                                    wtc
                                    xfiles
                                    xmas
                                    xmen
                                    xwing
                                    xxx
                                    y2k
                                    yacht
                                    yak
                                    yam
                                    yawn
                                    yellosub
                                    yellow
                                    yinyang
                                    ymca
                                    yoda
                                    yoga
                                    yoyo
                                    yuck
                                    zap
                                    zappa
                                    zebra
                                    zeppelin
                                    ziggurat
                                    ziggy
                                    zip
                                    zipper
                                    zippo
                                    zodiac
                                    zombie
                                    zoo
                                    zorro
                                    zulu
            """,decode("Ymx1ZQ"));
        @property
        def decoration(self):
            """ decoration, reverse, color, bg_color """
            return cs(decor(
                getattr(self,"Options")["decoration"],
                getattr(self,"Options")["reverse"]),
                getattr(self,"Options")["color"],
                getattr(self,"Options")["bg_color"]);
        @property
        def font(self):
            """ string, font, color, bg_color """
            return cs(text2art(
                getattr(self,"Options")["string"],
                getattr(self,"Options")["font"]),
                getattr(self,"Options")["color"],
                getattr(self,"Options")["bg_color"]);
        @property
        def strings(self):
            """ string, color ,bg_color """
            return cs(
                getattr(self,"Options")["string"],
                getattr(self,"Options")["color"],
                getattr(self,"Options")["bg_color"]);
        def url_strings(self,Attribute=None,Class=None):
            setattr(self,"setOpt",(BeautifulSoup(get(getattr(self,"Options")["url"]).content,"html.parser")));
            if Attribute == None or Class == None:
                setattr(self,"setCtn",(getattr(self,"setOpt").text));
                return cs(getattr(self,"setCtn").strip(),getattr(self,"Options")["color"],getattr(self,"Options")["bg_color"]);
            else:
                for i in getattr(self,"setOpt").findAll(Attribute,{"class":"%s"%(Class)}):
                    return cs(i.text.strip(),getattr(self,"Options")["color"],getattr(self,"Options")["bg_color"]);
        @property
        def textArt(self):
            """ string, font, decoration, color, bg_color """
            return (cs(text2art(
                getattr(self,"Options")["string"],
                getattr(self,"Options")["font"],
                decoration=getattr(self,"Options")["decoration"]),
                getattr(self,"Options")["color"],
                getattr(self,"Options")["bg_color"]));
        @property
        def random_font(self):
            """ string, font1, font2, font3, font4, color, bg_color """
            return choice([
                cs(text2art(getattr(self,"Options")["string"],getattr(self,"Options")["font1"]),getattr(self,"Options")["color"],getattr(self,"Options")["bg_color"]),
                cs(text2art(getattr(self,"Options")["string"],getattr(self,"Options")["font2"]),getattr(self,"Options")["color"],getattr(self,"Options")["bg_color"]),
                cs(text2art(getattr(self,"Options")["string"],getattr(self,"Options")["font3"]),getattr(self,"Options")["color"],getattr(self,"Options")["bg_color"]),
                cs(text2art(getattr(self,"Options")["string"],getattr(self,"Options")["font4"]),getattr(self,"Options")["color"],getattr(self,"Options")["bg_color"])]);
        @property
        def list_font(self):
            """ Semua list font """
            return cs(font_list(
                decode("a2FtYWJheQ")),
                decode("Z3JlZW4"));
        @property
        def list_art(self):
            """ Semua list art """
            return cs(art_list(),
            decode("Z3JlZW4"));
        @property
        def list_decoration(self):
            """ Semua list decorasi """
            return cs(decor_list(
                decode("a2FtYWJheQ"),
                decode("ZmFuY3k1")),
                decode("Z3JlZW4"));
        @property
        def list_ascii_art(self):
            """  category """
            setattr(self,"getContent",(BeautifulSoup(get("https://ascii.co.uk/art/%s"%(getattr(self,"Options")["category"])).content,"html.parser")));
            for container in getattr(self,"getContent").findAll("pre"):
                setattr(self,"move1",(container.text.strip()));
                return cs(getattr(self,"move1"),"green");
